name: Deploy Multiple PDFs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write    # Permite que o GITHUB_TOKEN faça push na branch gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LaTeX and required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Compile all LaTeX files
        run: |
          mkdir -p out
          find . -name "*.tex" | while read tex_file; do
            echo "Compiling $tex_file..."
            latexmk -pdf -outdir=./out "$tex_file"
          done

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: ./out/*.pdf

      - name: Deploy PDFs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: out
          GIT_CONFIG_NAME: github-actions-bot
          GIT_CONFIG_EMAIL: bot@noreply.github.com
